# Generated by Django 6.0.5 on 2026-05-09 09:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='adresse email')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='numéro de téléphone')),
                ('is_agent', models.BooleanField(default=False, verbose_name='est agent terrain')),
                ('is_client', models.BooleanField(default=True, verbose_name='est client')),
                ('is_verified', models.BooleanField(default=False, verbose_name='profil vérifié (KYC)')),
                ('reliability_score', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('punctuality_score', models.FloatField(default=100.0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('referral_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('id_card_number', models.CharField(blank=True, max_length=64, verbose_name='numéro de pièce ID')),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='kyc/ids/', verbose_name='Recto Pièce ID')),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='kyc/ids/', verbose_name='Verso Pièce ID')),
                ('selfie_with_id', models.ImageField(blank=True, null=True, upload_to='kyc/selfies/', verbose_name='Photo avec pièce en main')),
                ('witness_1_name', models.CharField(blank=True, max_length=255, verbose_name='Nom Témoin 1')),
                ('witness_1_phone', models.CharField(blank=True, max_length=20, verbose_name='Tel Témoin 1')),
                ('witness_2_name', models.CharField(blank=True, max_length=255, verbose_name='Nom Témoin 2')),
                ('witness_2_phone', models.CharField(blank=True, max_length=20, verbose_name='Tel Témoin 2')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='photo de profil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
