# Generated by Django 6.0.5 on 2026-05-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SUBMITTED', 'Soumis'), ('VERIFIED', 'Verifie'), ('REJECTED', 'Rejete')], default='PENDING', max_length=20),
        ),
    ]
