# Generated by Django 6.0.5 on 2026-06-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_referral_deeplink_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='referral_code_cache',
            field=models.CharField(blank=True, default='', help_text='Code influenceur capturé via deep link avant inscription', max_length=80, verbose_name='code parrainage (deep link)'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='referral_slug',
            field=models.SlugField(blank=True, help_text='Deep link ex: INFLU_BENIN → fonaco.app/join/INFLU_BENIN', max_length=80, null=True, unique=True, verbose_name='slug parrainage'),
        ),
    ]
