# Generated by Django 6.0.5 on 2026-06-19 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='contract_started_at',
            field=models.DateField(blank=True, help_text='Par défaut : date de création', null=True, verbose_name='début contrat'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='portal_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencer_portal', to=settings.AUTH_USER_MODEL, verbose_name='compte portail'),
        ),
        migrations.CreateModel(
            name='InfluencerWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='montant')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], db_index=True, default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, verbose_name='note influenceur')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='influencer/payout_proofs/', verbose_name='preuve de versement')),
                ('admin_note', models.TextField(blank=True, verbose_name='note admin')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='accounts.influencer')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_influencer_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demande retrait influenceur',
                'verbose_name_plural': 'demandes retrait influenceurs',
                'ordering': ['-requested_at'],
            },
        ),
    ]
