# Generated by Django 6.0.5 on 2026-06-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_influencer_portal_withdrawals'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='motif rejet KYC'),
        ),
        migrations.AddField(
            model_name='user',
            name='expertises',
            field=models.CharField(blank=True, help_text='Liste séparée par des virgules', max_length=500, verbose_name='expertises spécifiques agent'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='kyc_status',
            field=models.CharField(choices=[('NONE', 'Non soumis'), ('SUBMITTED', 'Soumis'), ('PENDING', 'En attente'), ('APPROVED', 'Approuve'), ('REJECTED', 'Rejete')], default='NONE', max_length=20),
        ),
    ]
