# Generated by Django 6.0.5 on 2026-06-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_agentprofile_veteran_boost_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Moyenne des notes reçues des clients (1-5)', max_digits=3, verbose_name='note moyenne'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='ratings_count',
            field=models.IntegerField(default=0, help_text='Nombre total de notes reçues', verbose_name='nombre de notes'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Moyenne des notes reçues des agents (1-5)', max_digits=3, verbose_name='note moyenne'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='ratings_count',
            field=models.IntegerField(default=0, help_text='Nombre total de notes reçues', verbose_name='nombre de notes'),
        ),
    ]
