# Generated by Django 6.0.5 on 2026-06-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_agentprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='completion_rate',
            field=models.FloatField(default=0.0, help_text='Pourcentage de missions complétées avec succès (0-100)', verbose_name='taux de complétion'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='ranking_score',
            field=models.FloatField(default=0.0, help_text='Score métier calculé pour le classement des agents (0-100)', verbose_name='score de classement'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='response_time_avg',
            field=models.FloatField(default=0.0, help_text='Temps moyen en secondes entre notification et acceptation de mission', verbose_name='temps de réponse moyen'),
        ),
    ]
