# Generated by Django 6.0.5 on 2026-06-20 16:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_agentprofile_completion_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRewardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, help_text='Points accumulés par le client', verbose_name='points de fidélité')),
                ('level', models.IntegerField(default=1, help_text='Niveau de fidélité (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='niveau de fidélité')),
                ('total_missions_completed', models.IntegerField(default=0, help_text='Nombre total de missions complétées', verbose_name='missions complétées')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant total dépensé en missions', max_digits=15, verbose_name='total dépensé')),
                ('badges_unlocked', models.JSONField(blank=True, default=list, help_text='Liste des badges débloqués (IDs)', verbose_name='badges débloqués')),
                ('last_points_earned_at', models.DateTimeField(blank=True, null=True, verbose_name='derniers points gagnés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil fidélité client',
                'verbose_name_plural': 'profils fidélité clients',
            },
        ),
    ]
