# Generated by Django 6.0.5 on 2026-06-21 18:12

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_clientrewardprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='badge_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models._UuidUpload('badges/photos'), verbose_name='photo badge professionnel'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='id_card_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models._UuidUpload('kyc/agent_ids'), verbose_name="photo recto pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='selfie_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models._UuidUpload('kyc/agent_selfies'), verbose_name='selfie avec pièce'),
        ),
    ]
