# Generated by Django 6.0.5 on 2026-06-21 18:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_uuid_upload_kyc_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('reward_type', models.CharField(choices=[('DISCOUNT', 'Réduction mission'), ('FREE_MISSION', 'Mission gratuite'), ('BONUS', 'Bonus portefeuille'), ('GIFT', 'Cadeau physique')], max_length=20, verbose_name='type')),
                ('points_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='coût en points')),
                ('value_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valeur FCFA')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='icône emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('stock', models.IntegerField(blank=True, help_text='Null = illimité', null=True, verbose_name='stock disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'récompense',
                'verbose_name_plural': 'récompenses',
                'ordering': ['points_cost'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.IntegerField(verbose_name='points dépensés')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('COMPLETED', 'Complété')], default='PENDING', max_length=20, verbose_name='statut')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='accounts.rewarditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'redemption',
                'verbose_name_plural': 'redemptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
