# Generated by Django 6.0.5 on 2026-06-23 18:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_reward_catalog_redemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.02'), help_text='Part du montant brut mission perçue par le manager (ex: 0.02 = 2 %)', max_digits=5, verbose_name='taux de commission')),
                ('max_agents', models.PositiveIntegerField(default=10, help_text="Nombre maximum d'agents dans la brigade", verbose_name='capacité brigade')),
                ('earnings_balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='solde commissions')),
                ('bio', models.TextField(blank=True, default='', verbose_name='présentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_manager_portal', to=settings.AUTH_USER_MODEL, verbose_name='compte portail')),
            ],
            options={
                'verbose_name': 'manager de brigade',
                'verbose_name_plural': 'managers de brigade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='accounts.teammanager', verbose_name='manager de brigade'),
        ),
    ]
