# Generated by Django 6.0.5 on 2026-05-16 08:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('delivery', 'Livraison'), ('service', 'Service'), ('transport', 'Transport'), ('assistance', 'Assistance'), ('other', 'Autre')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('client_notes', models.TextField(blank=True)),
                ('agent_feedback', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('withdrawn', 'Retirée')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_applications', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('distance_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skills_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('availability_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rating_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_matches', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status', '-created_at'], name='opportuniti_status_175007_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['type', 'priority'], name='opportuniti_type_adc6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['client', '-created_at'], name='opportuniti_client__0024c9_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['assigned_agent', '-created_at'], name='opportuniti_assigne_1f735e_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['expires_at'], name='opportuniti_expires_493cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityapplication',
            index=models.Index(fields=['opportunity', 'status'], name='opportuniti_opportu_0eed88_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityapplication',
            index=models.Index(fields=['agent', '-created_at'], name='opportuniti_agent_i_9853f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunityapplication',
            unique_together={('opportunity', 'agent')},
        ),
        migrations.AddIndex(
            model_name='opportunitymatch',
            index=models.Index(fields=['opportunity', '-match_score'], name='opportuniti_opportu_49f7c8_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitymatch',
            index=models.Index(fields=['agent', '-match_score'], name='opportuniti_agent_i_305962_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitymatch',
            index=models.Index(fields=['-match_score'], name='opportuniti_match_s_f0bd61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunitymatch',
            unique_together={('opportunity', 'agent')},
        ),
    ]
