# Generated by Django 6.0.5 on 2026-06-21 19:56

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('WALLET_DEPOSIT', 'Dépôt wallet'), ('FEEXPAY_DEPOSIT', 'Dépôt FeexPay'), ('WALLET_WITHDRAWAL', 'Retrait wallet'), ('PAYOUT_REQUEST', 'Demande retrait'), ('PAYOUT_APPROVED', 'Retrait approuvé'), ('PAYOUT_REJECTED', 'Retrait rejeté'), ('ESCROW_LOCK', 'Blocage séquestre'), ('ESCROW_RELEASE', 'Libération séquestre'), ('ESCROW_REFUND', 'Remboursement séquestre'), ('MISSION_PAYMENT', 'Paiement mission'), ('BOOST_PURCHASE', 'Achat boost'), ('BOOST_REFUND', 'Remboursement boost'), ('POINTS_AWARDED', 'Points attribués'), ('POINTS_REDEEMED', 'Points échangés'), ('MANUAL_ADJUSTMENT', 'Ajustement manuel'), ('CORRECTION', 'Correction erreur'), ('REVERSAL', 'Annulation')], db_index=True, max_length=50)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('debit_account', models.CharField(db_index=True, max_length=100)),
                ('credit_account', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('transaction_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('mission_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ledger',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['reference'], name='ledger_referen_c6e67b_idx'), models.Index(fields=['occurred_at'], name='ledger_occurre_c9990d_idx'), models.Index(fields=['entry_type'], name='ledger_entry_t_0eb2ef_idx'), models.Index(fields=['debit_account'], name='ledger_debit_a_abd28a_idx'), models.Index(fields=['credit_account'], name='ledger_credit__563efa_idx'), models.Index(fields=['transaction_id'], name='ledger_transac_2d78d7_idx'), models.Index(fields=['user_id'], name='ledger_user_id_706d98_idx'), models.Index(fields=['mission_id'], name='ledger_mission_4d8160_idx')],
            },
        ),
    ]
