# Generated by Django 6.0.5 on 2026-06-21 23:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('MISMATCH', 'Écart détecté'), ('ERROR', 'Erreur')], db_index=True, max_length=20)),
                ('wallets_checked', models.PositiveIntegerField(default=0)),
                ('mismatches_count', models.PositiveIntegerField(default=0)),
                ('mismatch_details', models.JSONField(blank=True, default=list)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'ledger_reconciliation_runs',
                'ordering': ['-run_at'],
                'indexes': [models.Index(fields=['-run_at'], name='ledger_reco_run_at_fb8706_idx'), models.Index(fields=['status', '-run_at'], name='ledger_reco_status_60c767_idx')],
            },
        ),
    ]
