# Generated by Django 6.0.5 on 2026-06-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leboncoin', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='locallisting',
            new_name='leboncoin_l_categor_53ef1c_idx',
            old_name='leboncoin_l_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='locallisting',
            new_name='leboncoin_l_city_7a0860_idx',
            old_name='leboncoin_l_city_di_idx',
        ),
    ]
