# Generated by Django 6.0.5 on 2026-06-13 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du plan')),
                ('duration_hours', models.IntegerField(verbose_name='Durée (heures)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('visibility_multiplier', models.DecimalField(decimal_places=1, default=1.5, max_digits=3, verbose_name='Multiplicateur de visibilité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Plan de Boost',
                'verbose_name_plural': 'Plans de Boost',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='AgentBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de début')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé (FCFA)')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boosts', to='boosts.boostplan')),
            ],
            options={
                'verbose_name': 'Boost Agent',
                'verbose_name_plural': 'Boosts Agents',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['agent', 'status'], name='boosts_agen_agent_i_777ffb_idx'), models.Index(fields=['expires_at'], name='boosts_agen_expires_0bde5b_idx')],
            },
        ),
    ]
