# Generated by Django 6.0.5 on 2026-05-09 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('HELD', 'Fonds bloqués'), ('RELEASED', 'Fonds libérés'), ('REFUNDED', 'Remboursé au client'), ('DISPUTED', 'En litige')], default='HELD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='missions.mission')),
            ],
            options={
                'verbose_name': 'Séquestre',
                'verbose_name_plural': 'Séquestres',
            },
        ),
    ]
