# Generated by Django 6.0.5 on 2026-05-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('HELD', 'Fonds bloques'), ('RELEASED', 'Fonds liberes'), ('REFUNDED', 'Rembourse au client'), ('DISPUTED', 'En litige')], default='HELD', max_length=20),
        ),
    ]
