# Generated by Django 6.0.5 on 2026-06-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_escrowsplitrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='escrowsplitrecord',
            new_name='escrow_escr_mission_6c0ddc_idx',
            old_name='escrow_escr_mission_idx',
        ),
        migrations.RenameIndex(
            model_name='escrowsplitrecord',
            new_name='escrow_escr_benefic_aacba2_idx',
            old_name='escrow_escr_benefic_idx',
        ),
        migrations.AlterField(
            model_name='escrowsplitrecord',
            name='beneficiary_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('CLIENT', 'Client'), ('PLATFORM', 'Plateforme FONACO'), ('INFLUENCER', 'Influenceur')], max_length=20),
        ),
    ]
