# Generated by Django 6.0.5 on 2026-06-23 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_team_manager_brigade'),
        ('escrow', '0003_rename_escrow_escr_mission_idx_escrow_escr_mission_6c0ddc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowsplitrecord',
            name='team_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_split_records', to='accounts.teammanager'),
        ),
        migrations.AlterField(
            model_name='escrowsplitrecord',
            name='beneficiary_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('CLIENT', 'Client'), ('PLATFORM', 'Plateforme FONACO'), ('INFLUENCER', 'Influenceur'), ('MANAGER', 'Manager de Brigade')], max_length=20),
        ),
    ]
