# Generated by Django 6.0.5 on 2026-06-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admin_audit_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='core_admina_action_0bd741_idx',
            old_name='core_admina_action_0a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='core_admina_target__fe6871_idx',
            old_name='core_admina_target__b4e1c9_idx',
        ),
        migrations.RenameIndex(
            model_name='adminnotification',
            new_name='core_adminn_is_read_9f75fd_idx',
            old_name='core_adminn_is_read_idx',
        ),
        migrations.RenameIndex(
            model_name='adminnotification',
            new_name='core_adminn_categor_51270c_idx',
            old_name='core_adminn_categor_idx',
        ),
    ]
