# Generated by Django 6.0.5 on 2026-05-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Reussi'), ('FAILED', 'Echoue')], default='PENDING', max_length=20),
        ),
    ]
