# Generated by Django 6.0.5 on 2026-06-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_purpose_metadata_amount_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de transaction unique du fournisseur de paiement (FeexPay, FedaPay, etc.) pour idempotency', max_length=100, null=True, unique=True),
        ),
    ]
