# Generated by Django 6.0.5 on 2026-05-12 20:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NOVICE', 'Novice'), ('VERIFIED', 'Verifie'), ('EXPERT', 'Expert')], max_length=50)),
                ('min_missions', models.PositiveIntegerField(default=0)),
                ('priority_boost', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='BoostPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_hours', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority_score', models.FloatField(default=2.0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_until', models.DateTimeField()),
                ('zone', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.boostplan')),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_REVIEW', 'En examen'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé')], default='OPEN', max_length=20)),
                ('admin_decision', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='disputes/evidences/')),
                ('description', models.CharField(max_length=255)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='missions.dispute')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTag',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tag',
                'verbose_name_plural': 'historical tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptee'), ('ON_THE_WAY', 'En route'), ('ARRIVED', 'Arrive sur place'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminee'), ('CANCELLED', 'Annulee'), ('DISPUTED', 'En litige')], default='PENDING', max_length=20)),
                ('qr_code_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True)),
                ('requires_procuration', models.BooleanField(default=False, help_text='La mission nécessite une procuration')),
                ('target_agent_username', models.CharField(blank=True, help_text="Username de l'agent cible si assignation manuelle", max_length=150, null=True)),
                ('start_photo', models.ImageField(blank=True, null=True, upload_to='missions/proofs/start/')),
                ('end_photo', models.ImageField(blank=True, null=True, upload_to='missions/proofs/end/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_assigned', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_ordered', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='missions.tag')),
            ],
        ),
        migrations.AddField(
            model_name='dispute',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_record', to='missions.mission'),
        ),
        migrations.CreateModel(
            name='MissionStats',
            fields=[
            ],
            options={
                'verbose_name': '💰 Tableau de Bord Financier',
                'verbose_name_plural': '💰 Tableaux de Bord Financiers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('missions.mission',),
        ),
        migrations.CreateModel(
            name='MissionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission')),
            ],
        ),
        migrations.CreateModel(
            name='MissionTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptee'), ('ON_THE_WAY', 'En route'), ('ARRIVED', 'Arrive sur place'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminee'), ('CANCELLED', 'Annulee'), ('DISPUTED', 'En litige')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('proof_photo', models.ImageField(blank=True, null=True, upload_to='missions/timeline/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='missions.mission')),
            ],
        ),
    ]
