# Generated by Django 6.0.5 on 2026-05-09 00:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Agent',
                'verbose_name_plural': 'Services Agents',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la mission')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordonnées GPS')),
                ('address', models.CharField(max_length=500, verbose_name='Adresse textuelle')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de la mission')),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Frais de plateforme')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('ON_THE_WAY', 'En route'), ('ARRIVED', 'Arrivé sur place'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée'), ('DISPUTED', 'En litige')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('qr_code_token', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Token QR Code de validation')),
                ('start_photo', models.ImageField(blank=True, null=True, upload_to='missions/proofs/start/', verbose_name='Photo de début')),
                ('end_photo', models.ImageField(blank=True, null=True, upload_to='missions/proofs/end/', verbose_name='Photo de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Agent (Waiter)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_ordered', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='missions.mission')),
            ],
            options={
                'verbose_name': 'Point de suivi GPS',
                'verbose_name_plural': 'Points de suivi GPS',
                'ordering': ['timestamp'],
            },
        ),
    ]
