
# Generated by Django 6.0.5 on 2026-05-09 11:16

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlevel',
            name='name',
            field=models.CharField(choices=[('NOVICE', 'Novice'), ('VERIFIED', 'Verifie'), ('EXPERT', 'Expert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptee'), ('ON_THE_WAY', 'En route'), ('ARRIVED', 'Arrive sur place'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminee'), ('CANCELLED', 'Annulee'), ('DISPUTED', 'En litige')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='missiontimeline',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptee'), ('ON_THE_WAY', 'En route'), ('ARRIVED', 'Arrive sur place'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminee'), ('CANCELLED', 'Annulee'), ('DISPUTED', 'En litige')], max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalTag',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tag',
                'verbose_name_plural': 'historical tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
