# Generated by Django 6.0.5 on 2026-05-30 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_dispute_disputeevidence_historicaltag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='agent_comment',
            field=models.TextField(blank=True, help_text="Commentaire de l'agent sur le client"),
        ),
        migrations.AddField(
            model_name='mission',
            name='agent_rating',
            field=models.IntegerField(blank=True, help_text="Note donnée par l'agent au client (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='mission',
            name='client_comment',
            field=models.TextField(blank=True, help_text="Commentaire du client sur l'agent"),
        ),
        migrations.AddField(
            model_name='mission',
            name='client_rating',
            field=models.IntegerField(blank=True, help_text="Note donnée par le client à l'agent (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
