# Generated by Django 6.0.5 on 2026-05-10 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_alter_agentlevel_name_alter_mission_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missionstats',
            options={'verbose_name': '💰 Tableau de Bord Financier', 'verbose_name_plural': '💰 Tableaux de Bord Financiers'},
        ),
    ]
