# Generated by Django 6.0.5 on 2026-06-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_mission_is_urgent_is_confidential_amounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disputeevidence',
            name='dispute',
        ),
        migrations.DeleteModel(
            name='Dispute',
        ),
        migrations.DeleteModel(
            name='DisputeEvidence',
        ),
    ]
