# Generated by Django 6.0.5 on 2026-06-09 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_remove_duplicate_dispute_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceMissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, help_text='Fichier audio original', null=True, upload_to='voice_missions/%Y/%m/%d/')),
                ('transcription', models.TextField(blank=True, default='')),
                ('transcription_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 de la transcription normalisée (anti-doublon)', max_length=64)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('missing_fields', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'En cours'), ('complete', 'Complet'), ('incomplete', 'Incomplet'), ('duplicate', 'Doublon détecté'), ('error', 'Erreur')], default='processing', max_length=20)),
                ('category_id_resolved', models.IntegerField(blank=True, help_text='ID services.Category résolu par find_best_category()', null=True)),
                ('category_name_resolved', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(blank=True, help_text='Mission créée depuis cette demande vocale (si confirmée)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_requests', to='missions.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande Mission Vocale',
                'verbose_name_plural': 'Demandes Mission Vocale',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'transcription_hash'], name='missions_vo_user_id_5a9114_idx')],
            },
        ),
    ]
