# Generated by Django 6.0.5 on 2026-06-09 19:12

import django.db.models.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_voice_mission_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemissionrequest',
            name='audio_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 du fichier audio (anti-doublon upload)', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='voicemissionrequest',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('user', 'audio_hash', 'transcription_hash'), name='unique_voice_request_hash'),
        ),
    ]
