# Generated by Django 6.0.5 on 2026-06-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_voicemissionrequest_audio_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='description_audio',
            field=models.FileField(blank=True, null=True, upload_to='missions/voice/%Y/%m/%d/', verbose_name='Description vocale (audio)'),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_vocal_description',
            field=models.BooleanField(default=False, help_text='La description de la mission est un enregistrement vocal joint'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='Agent interne Fonaqo : recruté et encadré par Fonaqo (+500 FCFA)'),
        ),
    ]
