# Generated by Django 6.0.5 on 2026-06-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_vocal_description_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptee'), ('ON_THE_WAY', 'En route'), ('ARRIVED', 'Arrive sur place'), ('IN_PROGRESS', 'En cours'), ('IN_PROGRESS_REVIEW', 'En attente validation client'), ('COMPLETED', 'Terminee'), ('CANCELLED', 'Annulee'), ('DISPUTED', 'En litige')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='missiontimeline',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptee'), ('ON_THE_WAY', 'En route'), ('ARRIVED', 'Arrive sur place'), ('IN_PROGRESS', 'En cours'), ('IN_PROGRESS_REVIEW', 'En attente validation client'), ('COMPLETED', 'Terminee'), ('CANCELLED', 'Annulee'), ('DISPUTED', 'En litige')], max_length=20),
        ),
    ]
