# Generated by Django 6.0.5 on 2026-06-21 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0013_mission_tracking_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='loyalty_points_awarded',
            field=models.BooleanField(default=False, help_text='True une fois que les points de fidélité ont été attribués au client (idempotent)'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['status', '-created_at'], name='missions_mi_status_1a88e7_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['client', 'status'], name='missions_mi_client__274a39_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['agent', 'status'], name='missions_mi_agent_i_ccd215_idx'),
        ),
    ]
