# Generated by Django 6.0.5 on 2026-06-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0014_add_loyalty_points_awarded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionRecommendation',
        ),
    ]
