# Generated by Django 6.0.5 on 2026-05-09 11:16

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Completee'), ('FAILED', 'Echouee'), ('CANCELLED', 'Annulee')], default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait'), ('MISSION_PAYMENT', 'Paiement de mission'), ('ESCROW_LOCK', 'Blocage Séquestre'), ('ESCROW_RELEASE', 'Libération Séquestre'), ('BOOST_PAYMENT', 'Achat de Boost'), ('REFERRAL_BONUS', 'Bonus Parrainage'), ('INSURANCE_FEE', 'Frais Assurance'), ('TRANSFER', 'Transfert')], max_length=20, verbose_name='Type de transaction'),
        ),
        migrations.CreateModel(
            name='HistoricalWallet',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Solde disponible')),
                ('escrow_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Solde en séquestre')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Portefeuille',
                'verbose_name_plural': 'historical Portefeuilles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
