# Generated by Django 6.0.5 on 2026-06-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_payoutrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payoutrequest',
            new_name='wallets_pay_status_ef4d6b_idx',
            old_name='wallets_pay_status_idx',
        ),
    ]
