# Generated by Django 6.0.5 on 2026-06-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_payoutrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait'), ('MISSION_PAYMENT', 'Paiement de mission'), ('ESCROW_LOCK', 'Blocage Séquestre'), ('ESCROW_RELEASE', 'Libération Séquestre'), ('BOOST_PAYMENT', 'Achat de Boost'), ('REFERRAL_BONUS', 'Bonus Parrainage'), ('INSURANCE_FEE', 'Frais Assurance'), ('TRANSFER', 'Transfert'), ('BADGE_FEE', 'Badge Professionnel')], max_length=20, verbose_name='Type de transaction'),
        ),
    ]
