# Generated by Django 6.0.5 on 2026-06-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='provider_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de transaction unique du fournisseur Mobile Money pour idempotency callback', max_length=100, null=True, unique=True),
        ),
    ]
