# Generated by Django 6.0.5 on 2026-06-20 15:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0013_mission_tracking_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_type', models.CharField(choices=[('CLIENT_RATES_AGENT', 'Client note agent'), ('AGENT_RATES_CLIENT', 'Agent note client')], max_length=30)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='missions.mission')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notation',
                'verbose_name_plural': 'Notations',
                'indexes': [models.Index(fields=['mission', 'rating_type'], name='ratings_rat_mission_80f990_idx'), models.Index(fields=['reviewee', '-created_at'], name='ratings_rat_reviewe_02375c_idx')],
                'unique_together': {('mission', 'reviewer', 'rating_type')},
            },
        ),
    ]
