# Generated by Django 6.0.5 on 2026-06-11 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0007_voicemissionrequest_audio_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du litige')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='disputes/evidence/%Y/%m/%d/', verbose_name='Preuve (image / document)')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('under_review', "En cours d'examen"), ('resolved', 'Résolu'), ('closed', 'Fermé'), ('escalated', 'Escaladé')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=10)),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Notes de résolution')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant remboursé (FCFA)')),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pénalité appliquée (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='missions.mission')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Litige',
                'verbose_name_plural': 'Litiges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Si vrai, visible uniquement par le staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='disputes.dispute')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='disputes/evidences/%Y/%m/%d/', verbose_name='Fichier preuve')),
                ('description', models.TextField(blank=True, verbose_name='Description de la preuve')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='disputes.dispute')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preuve',
                'verbose_name_plural': 'Preuves',
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', '-created_at'], name='disputes_di_status_e85bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['mission', '-created_at'], name='disputes_di_mission_225328_idx'),
        ),
    ]
