# Generated by Django 6.0.5 on 2026-06-09 16:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_message_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID v4 généré côté Flutter pour déduplication', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Distribué'), ('read', 'Lu')], default='sent', max_length=10),
        ),
        migrations.AddField(
            model_name='typingstatus',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="Expiration automatique du typing indicator (5 s d'inactivité)", null=True),
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('audio', 'Audio'), ('file', 'Fichier générique')], default='file', max_length=10)),
                ('file', models.FileField(upload_to='chat_attachments/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Taille en octets', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message')),
            ],
            options={
                'verbose_name': 'Pièce jointe chat',
                'verbose_name_plural': 'Pièces jointes chat',
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence utilisateur',
            },
        ),
    ]
