# Generated by Django 6.0.5 on 2026-06-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_client_message_id_delivery_status_attachment_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='negotiation_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant proposé (FCFA)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('voice', 'Vocal'), ('file', 'Fichier'), ('system', 'Système'), ('negotiation', 'Négociation tarif')], default='text', max_length=15),
        ),
    ]
