# Generated by Django 6.0.5 on 2026-06-21 21:51

import apps.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_negotiation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatattachment',
            name='file',
            field=models.FileField(upload_to='chat_attachments/%Y/%m/%d/', validators=[apps.core.validators.validate_chat_attachment]),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_voice/%Y/%m/%d/', validators=[apps.core.validators.validate_audio_upload]),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_media/%Y/%m/%d/', validators=[apps.core.validators.validate_chat_media]),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'client_message_id'], name='message_conv_client_id_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'delivery_status', 'created_at'], name='message_delivery_idx'),
        ),
    ]
